# Generated by Django 2.2.14 on 2021-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'mobiles'), ('Camera', 'Camera'), ('Laptop', 'Laptop'), ('Macbook', 'Macbook'), ('Accessories', 'accessories'), ('Others', 'Others')], max_length=120),
        ),
    ]
